# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
    gatekeeper:
        image: gatekeeper
        build:
            context: .
            dockerfile: Gatekeeper/Dockerfile
        ports:
            - 4040:4040
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - ~/.vsdbg:/remote_debugger:rw
